### ISSUE TITLE
FontAwesome.Sharp package (v5.15.4.0) is unsigned

### ISSUE THREAD

**Issue by Xcoder62** [awesome-inc/FontAwesome.Sharp#100]
**Describe the bug**
FontAwesome.Sharp package (v5.15.4.0) is unsigned and therefore our project can not be deployed via Clickonce with the unsigned package.

**Expected behavior**
Once the FontAwesome.Sharp package (v5.15.4.0) is signed and we can deploy our project with Clickonce and include FontAwesome.Sharp.

**Comment by mkoertgen** [comment]
Hi @Xcoder62 ,

We will not re-sign already published packages. I would suggest to update to a later version (if you can).
Other than that you can probably down-grade and use the community package https://www.nuget.org/packages/FontAwesome.Sharp.StrongName

For more details please refer to 
- Old documentation/FAQ: https://github.com/awesome-inc/FontAwesome.Sharp/tree/7e14c4e3f4a383f1f2914388423eb269f8b90fd2#strong-name-signing-eg-for-clickonce-publishing
- https://github.com/awesome-inc/FontAwesome.Sharp/issues/56
- https://github.com/awesome-inc/FontAwesome.Sharp/issues/89
