### ISSUE TITLE
Update NuGet Package to 6.2.1

### ISSUE THREAD

**Issue by felsenbirne** [awesome-inc/FontAwesome.Sharp#104]
With the Commit 0a8d51f9de3e31b8761b03beb49e47f028e7a909 the Repository was updated to support FontAwesome 6.2.1.

Yet, the NuGet Package on nuget.org is still on 6.1.1. 
Could you please update the NuGet Package to the current Version of the Repository?
Thank you.

**Comment by mkoertgen** [comment]
Hi @felsenbirne, 

From what I see, the current font in code in fact is `6.1.1` whereas the current release by [fortawesome is 6.2.1](https://www.npmjs.com/package/@fortawesome/fontawesome-free).

**Comment by mkoertgen** [comment]
Building at https://github.com/awesome-inc/FontAwesome.Sharp/actions/runs/3749087642

**Comment by mkoertgen** [comment]
See https://www.nuget.org/packages/FontAwesome.Sharp/6.2.1
