### ISSUE TITLE
Image and text are not horizontal aligned.

### ISSUE THREAD

**Issue by WilliamQue** [awesome-inc/FontAwesome.Sharp#109]
Please see the pic, the first control is a toolstriplabel, and the second is a icontoolstripbutton, there are 2 problems:
1. It seems that the horizontal central line of  image is a little higher than text on each control;
2. the horizontal central line of content on toolstriplabel is a little than that on icontoolsstripbutton.

For toolstriplabel :
```
 GlobalImageList.AddIcons(Color.Red, IconHelper.DefaultSize, new IconChar[] { IconChar.UserAlt});
 GlobalImageList.ImageSize = new Size(28,28);
 lblUser.Image = GlobalImageList.Images[2];
```

For icontoolstripbutton:  all settings are done in property wiindow directly.

Font of them is Microfoft Yahei UI.
Image Size : 28
Control with property ImageScaling will be set None.

![1](https://user-images.githubusercontent.com/38513709/215509273-cf407f1b-65c3-412f-a4ed-9e34f027b566.png)

Env: win10 + .net framework 4.8 + winform

**Comment by mkoertgen** [comment]
Hi @WilliamQue ,

Not sure what to do about it. Looks more like an alignment issue with the toolstrip label itself.
