### ISSUE TITLE
Update NuGet package FontAwesome.Sharp.Pro

### ISSUE THREAD

**Issue by felsenbirne** [awesome-inc/FontAwesome.Sharp#112]
The current version of the NuGet Package FontAwesome.Sharp.Pro contains a bug that was solved with the Pull Request #108 
Please update the package to make the bug fix available for NuGet users.

**Comment by mkoertgen** [comment]
Publishing 6.3.0...
https://github.com/awesome-inc/FontAwesome.Sharp/actions/runs/4331674157/jobs/7563657209

**Comment by mkoertgen** [comment]
Hi @felsenbirne,

Sorry for delayed responding. Pro 6.3.0 not yet indexed, yet will be available in a few minutes. Please check at your convenience.
