### ISSUE TITLE
Update NuGet package FontAwesome.Sharp.Pro

### ISSUE THREAD

**Issue by RickMannien** [awesome-inc/FontAwesome.Sharp#114]
Like mentioned in Issue #112 the changes of Pull Request #108 still are not present in the current NuGet package. Could you please have a second look and update the NuGet package?

**Comment by mkoertgen** [comment]
@RickMannien Sorry for responding late.

Changes have been merged and package pushed 5 months ago
- https://www.nuget.org/packages/FontAwesome.Sharp
- https://www.nuget.org/packages/FontAwesome.Sharp.Pro

How did you conclude changes are not present in the package?

**Comment by RickMannien** [comment]
No worries let me elaborate a bit more,

I get the exact same error as described in the orignal issue when using the NuGet packages. So I decided to pull from main and check whether or not the changes are present there.  I found that the changes to fix the pro package are not present. So I'm assuming that they also never made it to the NuGet package.

The changes can be found here: [https://github.com/awesome-inc/FontAwesome.Sharp/pull/108/files](url). I'm focussing on the changes in

- FontAwesome.Sharp.Pro/WPF/IconBlock.cs and,
- FontAwesome.Sharp.Pro/WPF/IconImage.cs

Where the type **IconFont** is changed to **ProIconFont**

I added these changes myself in a local version of the package which resolves the error for me.

Please tell me if I'm making a mistake somewhere, but I hope this helps

**Comment by mkoertgen** [comment]
I see, the pull request has been merged to the pro branch
- https://github.com/awesome-inc/FontAwesome.Sharp/pull/108/files

**Comment by mkoertgen** [comment]
Merged main + pro branches, updated to 6.4.2

**Comment by mkoertgen** [comment]
Should be fixed with the 6.4.2 update:-
- https://github.com/awesome-inc/FontAwesome.Sharp/actions/runs/5984503820

**Comment by nj** [comment]
@mkoertgen Assume you went a big quick in making this as completed, as the build end up failing, due to a bug in the main at that time.

It states `10 errors and 13 warnings`, so was never updated on [NuGet](https://www.nuget.org/packages/FontAwesome.Sharp.Pro) 😞 

Can it be rerun, perhaps bump version ?

Also made a PR #120, to reflect latest FA, so it can be included at the same time.

Thanks!
