### ISSUE TITLE
Font awesome for Sharp look up

### ISSUE THREAD

**Issue by ProgramistaZaDyszke** [awesome-inc/FontAwesome.Sharp#125]
http://fortawesome.github.io/Font-Awesome/cheatsheet/ - page is down. Any other place where I can easily look for icon names and how they look without reloading whole solution or play with hotReload? In my case I have data binding so it will not show me all names of icons and even then it is not quite comfortable to do so.

**Comment by nj** [comment]
Just use https://fontawesome.com/v6/search?o=r&m=free

Notice though that some icons might be missing due to current rendered NuGet package is being 6.3.0 whereas the most recent is 6.6.0. The changelog between the mentioned versions can be found at https://fontawesome.com/changelog.

**Comment by mkoertgen** [comment]
Thanks for your contributions @nj ♥️

Tagged the package with 6.6.0
