### ISSUE TITLE
Error with Awesome Pro on .net 8 winforms project

### ISSUE THREAD

**Issue by bmsengin** [awesome-inc/FontAwesome.Sharp#134]
**Describe the bug**
When I try to drag/drop a FontAwesome.Sharp control on a form I have an error

![image](https://github.com/user-attachments/assets/37c2623d-2a62-4753-8757-1051d1fc5107)

**To Reproduce**
1. I have install FontAwesome.Sharp.Pro

![image](https://github.com/user-attachments/assets/5f58f715-f583-439d-b17c-56cb3005b866)

2. I have embeded .ttf files

![image](https://github.com/user-attachments/assets/e386a1af-c843-4b4c-9832-5183963b8b4e)

**Comment by bmsengin** [comment]
I have found a part of the bug

In ProFonts.cs, duatone need to be put in comment :

`private static readonly string[] FontFiles =
{
    "fa-regular-400-pro.ttf",
    "fa-solid-900-pro.ttf",
    "fa-light-300-pro.ttf",
    "fa-thin-100-pro.ttf"
    //"fa-duotone-900-pro.ttf"
};`

**And** the font files inclued need to have correct name : 

fa-light-300-pro.ttf
fa-regular-400-pro.ttf
fa-solid-900-pro.ttf
fa-thin-100-pro.ttf

With this fix, it work by creating Control with code, but i have still the same error on VS conception mode

**Comment by mkoertgen** [comment]
Hi @bmsengin ,

Thanks for reaching out. It's been a while that someone used the pro-fonts on WinForms.
You might also try to regenerate & update the pro-enums as described in the [docs](https://awesome-inc.github.io/FontAwesome.Sharp/#using-fontawesome-pro).

Think about contributing with a pull-request. ❤️👌
