### ISSUE TITLE
Font Awesome Pro ?

### ISSUE THREAD

**Issue by mfruhner** [awesome-inc/FontAwesome.Sharp#15]
Hello,
I managed to implement this into our application, but now I am wondering, if you support FA Pro as well.
As our designer used almost Pro Icons only, this would be great. I could not find information about this in the project.

Greetings,
Maik

**Comment by mkoertgen** [comment]
Hm, at this time we don't support FA Pro, simply because we don't own a license by now.
But integrating FA font should be straight forward in a manner like we did for Material Design, cf.:

- https://github.com/awesome-inc/FontAwesome.Sharp#using-custom-fonts

**Comment by mkoertgen** [comment]
@mfruhner If you gonna try let me know how you are doing and we can probably help.

**Comment by leomurillo** [comment]
The steps I followed:

1. Download your pro web fonts. 
2. Identify in your downloaded web font files \css\fontawesome.css 
3. Replace fontawesome.css in \FontAwesome.Sharp\FontEnumGenerator\Content with this file
4. Run FontEnumGenerator, this will generate a new IconChar.cs
5. Replace \FontAwesome.Sharp\FontAwesome.Sharp\IconChar.cs with the newly generated one.
6. From the downloaded fonts copy the \webfonts\fa-*.ttf files, paste them at \FontAwesome.Sharp\FontAwesome.Sharp\fonts. Besides overwriting the three free font files, you will see two new ones: fa-duotone-900.ttf and fa-light-300.ttf.
7. Rebuild the FontAwesome.Sharp project. You'll get the new FontAwesome.Sharp.dll with all pro icons

If you get Invalid Assemby Errors when you first build. Add in Properties\AssemblyInfo.cs the following:
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]

**Comment by mkoertgen** [comment]
@leomurillo thanks for guidance in building the pro-version. Maybe we can add this to the docs?

**Comment by mkoertgen** [comment]
Closed due to inactivity
