### ISSUE TITLE
Update to v5.8.2

### ISSUE THREAD

**Issue by Willy-Kimura** [awesome-inc/FontAwesome.Sharp#19]
Thanks for the fantastic work so far.
There's a new FontAwesome update, **v5.8** with 118 new icons and brands.

**Comment by mkoertgen** [comment]
Thx @Willy-Kimura. Feedback much appreciated.

Update to 5.8.2 just pushed. Also includes some forms-fixes on looking up glyphs from fonts.

**Comment by Willy-Kimura** [comment]
Awesome! Very much appreciate the quick update and additions.
Reviewing and testing now... 👍
