### ISSUE TITLE
overloading ToBitmap with width/height params

### ISSUE THREAD

**Issue by dbhc** [awesome-inc/FontAwesome.Sharp#25]
FormsIconHelper's ToBitmap method only accepts a single size param.
For underlying fonts that are much wider than tall (or vice versa), it creates a much smaller image than intended.
Exposing a way to explicitly set the width and height would be helpful.

I created a fork with this change if you'd like to merge it.

**Comment by mkoertgen** [comment]
@dbhc I would love to merge it in. I created a pull request for it #26.
Out of curiosity: which font did you try?

**Comment by dbhc** [comment]
Cogs, UserCog, MoneyCheckAlt to name a few.
MoneyCheckAlt was the one that had the greatest width to height aspect ratio.

**Comment by mkoertgen** [comment]
Ah, i see. It was in fact some icons with a non-square aspect ratio. Ok, thanks.

**Comment by mkoertgen** [comment]
Merged with #26
