### ISSUE TITLE
Cannot add FontAwesome.Sharp.dll V-5.8.3 to toolbox

### ISSUE THREAD

**Issue by John0076** [awesome-inc/FontAwesome.Sharp#27]
Hello, I try to add the controls of the FontAwesome.Sharp library to the visual studio 2015 toolbox, with these steps:
add items to the tab, i.e. Choose Items -> Browse, then select $ (SolutionDir) ./ packages \ FontAwesome.Sharp.5.8.3 \ lib \ net40 \ FontAwesome.Sharp.dll

But I get the following error:

There are no items in '$ (SolutionDir) ... FontAwesome.Sharp.dll' that can be placed in the toolbox.

I get the same error in visual studio 2012-2015-2017-2019.
Although in VS 2017 and 2019 the controls are automatically added to the toolbox after installing from nuget.

**Comment by mkoertgen** [comment]
Hi @John0076, 
at first glance this seems to be related more to an existing VS issue than to FontAwesome.Sharp.

The closest issue we had with this has been added to the faq, cf.:

- https://github.com/awesome-inc/FontAwesome.Sharp#windows-forms-designer-i-cannot-find-any-controls-in-the-toolbox

Also, resetting the toolbox cache (.tbd) may help, as reported by users having general problems with the toolbox, e.g.

- https://social.msdn.microsoft.com/Forums/vstudio/en-US/17070063-5025-47b6-8a12-38fac1037e49/vs2013-toolbox-wont-add-my-controls?forum=visualstudiogeneral

**Comment by John0076** [comment]
thanks for replying and being aware :)
I will try to solve with the information provided.

**Comment by John0076** [comment]
thanks for replying and being aware :)
I will try to solve with the information provided.

**Comment by mkoertgen** [comment]
@John0076 Likewise, thx for reporting the issue. Let me know if it helps.

**Comment by John0076** [comment]
You're absolutely right, it's a VS error. It is no longer possible to add any type of control (that previously worked) to the toolbox from a dll library.
However I could not solve. I will keep looking for solutions. Otherwise I will reinstall the operating system and VS.

**Comment by John0076** [comment]
Hi, you cannot reset the cache of the toolbox of all versions of visual studio that I commented. I reinstalled everything- Now it works great. Thanks for your help and be aware :)
And I find an interesting tutorial with the font Awesome package- Thank you for creating this awesome library.
https://www.youtube.com/watch?v=5AsJJl7Bhvc

regards

**Comment by mkoertgen** [comment]
Awesome ;-) Thanks for the info on the YouTube-Tutorial! Probably a good idea to add a link to the ReadMe.

fyi @ThomasLey

**Comment by John0076** [comment]
Yes, it would be good to add to the readme file. It helped me understand how to use it, regards ;)

**Comment by Rapheal123-star** [comment]
Hi can I get the dll file for fontawesome.sharp

**Comment by mkoertgen** [comment]
Hi @Rapheal123-star ,

The easiest way is to download the nuget-package. It's just a zip-file. In the lib-folder you will find the dlls.
- https://www.nuget.org/packages/FontAwesome.Sharp
- Download the 6.1.1-version (direct link): https://www.nuget.org/api/v2/package/FontAwesome.Sharp/6.1.1
