### ISSUE TITLE
Animated icons

### ISSUE THREAD

**Issue by sectasy0** [awesome-inc/FontAwesome.Sharp#34]
How to use animated icons? from https://fontawesome.com/how-to-use/on-the-web/styling/animating-icons

**Comment by mkoertgen** [comment]
Hi @sectasy0 , thx for reaching out.

For WPF spinning is supported via the Spin-Markup-Extension, cf.:

- https://github.com/awesome-inc/FontAwesome.Sharp/blob/master/TestWpf/MainWindow.xaml#L119

For WinForms there is no comfortable built-in way to spin automagically via a behaviour but you can control the `Rotation` & `Flip`-properties, cf.:

- https://github.com/awesome-inc/FontAwesome.Sharp/blob/master/TestForms/MainForm.cs#L83
