### ISSUE TITLE
Solid Style with nuget?

### ISSUE THREAD

**Issue by foreachthing** [awesome-inc/FontAwesome.Sharp#38]
How can I change the lookup-order of chars with the nuget package?
I very much like the left char (solid) over the one on the right (regular):
![image](https://user-images.githubusercontent.com/10420187/84143983-c90a6600-aa57-11ea-80dd-88abdc606984.png)

**Comment by mkoertgen** [comment]
Hi @foreachthing,

As of now the lookup order is hard-coded, cf.:

- https://github.com/awesome-inc/FontAwesome.Sharp/blob/master/FontAwesome.Sharp/WPF/IconHelper.cs#L111

We did not add the style-concept yet. That would probably a good extension. The way i would go about is to add style-property in xaml, e.g.

```xaml
<fa:IconBlock Icon="Home" Foreground="Blue" Style="<Regular> or <Solid>" />
```

As a workaround you can always use the font explicitly in a [TextBlock (see Readme)](https://github.com/awesome-inc/FontAwesome.Sharp#text) like this

```xaml
<TextBlock Grid.Column="1" Text="&#xf042;"   <----- Use hex-code of "IconChar.FolderOpen" here
    FontFamily="/FontAwesome.Sharp;component/fonts/#Font Awesome 5 Free Solid"
    Foreground="Chartreuse"
    TextAlignment="Center" />
```

But of course then you lose most of the goodness FontAwesome.Sharp brings to the table ;-)

**Comment by foreachthing** [comment]
Thanks for your answer @mkoertgen 
I guess I should have mentioned that I am using Windows Forms (somehow I can't get used to wpf).
Any chance of using _solids_ with c#?

**Comment by mkoertgen** [comment]
Hi @foreachthing, 

You can always sub-class the component you want to use and override the [FontFor](https://github.com/awesome-inc/FontAwesome.Sharp/blob/master/FontAwesome.Sharp/WinForms/IconButton.cs#L14)-method. 

For example the `IconButton`:

```csharp
public class MyIconButton : IconButton
{
   public override FontFor(IconChar icon)
   {
        if (UseSolid)
           return ....
   }
}
```

As of now access to the internally loaded fonts is private/internal in [FormsIconHelper.cs](https://github.com/awesome-inc/FontAwesome.Sharp/blob/master/FontAwesome.Sharp/WinForms/FormsIconHelper.cs#L119) but it should be no problem to make this public.

**Comment by foreachthing** [comment]
Yeah ... !
I'm fairly new to c# and could not get it to work.

So, I adjusted the code according issue https://github.com/awesome-inc/FontAwesome.Sharp/issues/33, and that was it! :-)

Thanks for your patience and hard work.
