### ISSUE TITLE
Exception HRESULT: 0x800A01E1 (CTL_E_INVALIDPICTURE) while changing IconChar

### ISSUE THREAD

**Issue by aadi1295** [awesome-inc/FontAwesome.Sharp#40]
We experienced exception on installed software
```
************** Exception Text **************
System.Runtime.InteropServices.COMException (0x800A01E1): Exception from HRESULT: 0x800A01E1 (CTL_E_INVALIDPICTURE)
at System.Windows.Forms.UnsafeNativeMethods.IPersistStream.Load(IStream pstm)
at System.Windows.Forms.Cursor.LoadPicture(IStream stream)

```
when we try to change Icon of the button like code below
`markQuestionBtn.IconChar = FontAwesome.Sharp.IconChar.CheckSquare;`

What could be the issue?
OS Windows 10 Home and It's working fine on Windows 10 pro but having issue on Home edition only.

**Comment by mkoertgen** [comment]
Hi @aadi1295,
Sorry for not responding timely. I noticed you closed the issue again. Would you mind sharing your solution?
