### ISSUE TITLE
FontAwesome Sharp on high DPI Screens

### ISSUE THREAD

**Issue by aadi1295** [awesome-inc/FontAwesome.Sharp#41]
Hello,
How to use FontAwesome Sharp on high DPI screens?
I have an application developed in 1080p screen and now on 4K screen the icon buttons changes then whole forms look to very tiny and compact windows forms. 
when I remove the icon button and add the normal windows forms button everything is work and looks fine as it should be.
is there any guide that I can look at to set the icon buttons or icon picture box work on any DPI screen.

Looking forward to hearing from you. Thanks

**Comment by mkoertgen** [comment]
Hi @aadi1295,

Did you try enabling Dpi-Awareness? See the FAQ
- [My Windows Forms application gets rescaled once a FontAwesome-item is created](https://github.com/awesome-inc/FontAwesome.Sharp/blob/master/README.md#my-windows-forms-application-gets-rescaled-once-a-fontawesome-item-is-created)

**Comment by aadi1295** [comment]
@mkoertgen 
I have .Net 4.6.1 application. DPI awareness v2 is available in 4.7+(Only windows 10 support) so I can't do it unless I upgrade to 4.7.
I tried to do that in the manifest but didn't work.
My customers still have Windows 8 as well and on 4K displays so DPI awareness is not a solution for me right now.

**Comment by mkoertgen** [comment]
Sorry @aadi1295 , i have no ready-to-take solution for you other than reviewing the docs mentioned under the FAQ entry. WinForms has quite a bit of legacy.

**Comment by mkoertgen** [comment]
Closed due to inactivity
