### ISSUE TITLE
AddIcons causes UI glitches [Winforms]

### ISSUE THREAD

**Issue by milannankov** [awesome-inc/FontAwesome.Sharp#42]
Hi, 

First I would like to thank you for creating and supporting this project. 

My problem is as follows. Once I use AddIcons extension method from FormsIconHelper, all labels in my app get ellipses as if there is not enough space to render all text labels. As if AddIcons causes reevaluation of the layout. 

Here is the normal app:
![okay](https://user-images.githubusercontent.com/2611068/87837448-35b92180-c89c-11ea-82db-9ef4268035ca.PNG)

Here is the app after AddIcons
![ellipses](https://user-images.githubusercontent.com/2611068/87837463-423d7a00-c89c-11ea-8194-68d8818ecfb2.PNG)

Any help would be appreciated.

**Comment by milannankov** [comment]
I would like to add that I have enabled DPI awareness as described in your samples but the ellipses still appear.

**Comment by milannankov** [comment]
Some more information. I attached the source project to inspect what is going on but the strangest thing happens. As soon as I invoke some method on the Icon class for example, I get the ellipses and jumbled UI.

For example calling IconHelper.ToChar (only that method) will cause the problem with UI.

**Comment by mkoertgen** [comment]
Hi @milannankov,

Thanks for reaching out. I do not recall the semantics of "AddIcons" exactly on spot. Will look into this and get back to you.

**Comment by mkoertgen** [comment]
Hi @milannankov, 

I tried to reproduce without success, sorry. I understood that you invoked fa-methods at runtime after the app/forms initialized. You might try to initialize right in the forms ctor.

**Comment by mkoertgen** [comment]
Closed due to inactivity
