### ISSUE TITLE
FontAwesome icon NOT vertically aligned on controls

### ISSUE THREAD

**Issue by lordofscripts** [awesome-inc/FontAwesome.Sharp#43]
**Source:** NuGet 
**Package:** FontAwesome.Sharp
**Version:** v5.13
**Platform:** Windows Forms desktop application

I am using the FontAwesome.Sharp NuGet on my .NET (C#) Winforms project. I have used it to show FA icons on ToolStripMenuItems and Buttons and noticed that the icon is NOT vertically aligned on System.Windows.Forms controls. When the icon is displayed on the control, the icon looks shifted down so it does not look 'awesome'.

**Comment by mkoertgen** [comment]
Hi @lordofscripts ,

Thanks for reaching out. It seems that gdi+ string measuring is not 100% accurate but i could improve it a bit.

![image](https://user-images.githubusercontent.com/7235760/89509121-307e3100-d7cf-11ea-8576-744e3a814d8f.png)

Also updated fonts. Check with 5.14+

**Comment by lordofscripts** [comment]
Just updated to 5.14, I think some changes are needed in the FontAwesome.Sharp.IconPictureBox because the chosen icon is not centered in the IconPictureBox, is more like it is shifted upwards or up and to the right in the control. I was looking for some alignment properties but there was none.

**Comment by mkoertgen** [comment]
Hi @lordofscripts 

Thanks for investigating. If you have time to spare a PR would be much appreciated.

**Comment by lordofscripts** [comment]
Yes, exactly as in #44

**Comment by mkoertgen** [comment]
I was able to tackle this. Not 100% fine with this. Will probably need some days to publish a new release

**Comment by mkoertgen** [comment]
It looks like most issues can be fixed by avoiding under-sampling. Some time ago we pinned the default icon size to 16 pixels which is way too low for modern devices where 96 dpi is the norm.

Upgrading the default icon size to 48.
