### ISSUE TITLE
icon not centered

### ISSUE THREAD

**Issue by mayurjansari** [awesome-inc/FontAwesome.Sharp#44]
in previous version 5.13 icon was center but now in this 5.14 icon slightly right side
![5 13](https://user-images.githubusercontent.com/18002706/89777313-11620500-db29-11ea-9ca9-5a37879cc43c.png)
![5 14](https://user-images.githubusercontent.com/18002706/89777325-18891300-db29-11ea-8109-fa905440859b.png)

**Comment by mkoertgen** [comment]
Hi @mayurjansari ,

Thanks for investigating. If you have some time to spare a PR would be much appreciated.

**Comment by FernandoCalmet** [comment]
Hi. I have the same issue. This happens only in the latest version of the nugget.

**Comment by mkoertgen** [comment]
Hi @FernandoCalmet , thanks for confirming. It looks like fixing the vertical alignment with #43 impacted the horizontal alignment.

**Comment by mkoertgen** [comment]
After a quick google search it looks like [Graphics.MeasureString has accuracy issues](https://social.msdn.microsoft.com/Forums/windows/en-US/0d991394-4911-42b8-8cb5-7cd3c745c87b/graphicsmeasurestring-is-not-accurate?forum=winforms).

As an alternative let's check on 
- [TextRenderer.MeasureText](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.textrenderer.measuretext?view=netcore-3.1)
- [Graphics.MeasureCharacterRanges](https://docs.microsoft.com/en-us/dotnet/api/system.drawing.graphics.measurecharacterranges?view=dotnet-plat-ext-3.1)

as e.g. indicated in this ancient posts:
- https://www.codeproject.com/Articles/2118/Bypass-Graphics-MeasureString-limitations

**Comment by mkoertgen** [comment]
Fixed together with #43
