### ISSUE TITLE
Can fontawesome.sharp.iconchar be added to imagelist in windows forms"

### ISSUE THREAD

**Issue by LukB4ULeap** [awesome-inc/FontAwesome.Sharp#45]
Is this possible ? 
If Yes how ?

**Comment by mkoertgen** [comment]
Hi @LukB4ULeap ,

The sample application has an example for using an `AddIcons`-extension method, cf.:
- [TestForms/MainForm.cs#L43](https://github.com/awesome-inc/FontAwesome.Sharp/blob/master/TestForms/MainForm.cs#L43)
- [FontAwesome.Sharp/WinForms/FormsIconHelper.cs#L95](https://github.com/awesome-inc/FontAwesome.Sharp/blob/ef71643ca08ce47516404180e1821913bed98fce/FontAwesome.Sharp/WinForms/FormsIconHelper.cs#L95)

**Comment by mkoertgen** [comment]
Close due to inactivity
