### ISSUE TITLE
Icons not loading on .Net 5.0 preview 7

### ISSUE THREAD

**Issue by aeonSolutions** [awesome-inc/FontAwesome.Sharp#46]
Hello,
I've been migrating my code to .net 5.0 and found that font awesome sharp icons (not all but most of them) not load at all .
For example the icons ideal and faucet are working however the cogs and settings aren't. 
I've tried sorting the problem but without any luck.

**Comment by mkoertgen** [comment]
Hi @aeonSolutions,

Thanks for testing out. What did you try?

Probably i can join in the next few days. Right now, i have not much time to spare.

**Comment by mkoertgen** [comment]
Probably related to #47. I will check if the unicodes changed and probably regenerate the icon-enums. Did you also update the nuget-pakage to 5.14? Can you list some icons that defintely don't show up, e.g. FaCogs?

**Comment by aeonSolutions** [comment]
hello,
sorry for the late reply. 

i'm using the nuget 5.14 and still has the same problem.

meantime i see you merged with another #47

**Comment by mkoertgen** [comment]
Hi @aeonSolutions , 
Meanwhile @FoxCouncil provided a fix for #47 . Maybe 5.14.1 fixes this, too?

**Comment by mkoertgen** [comment]
Hi @aeonSolutions,

Only to be clear: You are referring to WinForms i guess?

**Comment by mkoertgen** [comment]
Hi @aeonSolutions ,

I just tried the "TestForms" application using the latest net5 preview. I could not find any issues, e.g. the cog-icon works just fine.

Feel free to review & check out the [net5-branch](https://github.com/awesome-inc/FontAwesome.Sharp/tree/net5)

![image](https://user-images.githubusercontent.com/7235760/95883304-10449280-0d7b-11eb-845a-ad52d3bcb316.png)

**Comment by aeonSolutions** [comment]
ok. thanks. i will.

**Comment by mkoertgen** [comment]
Basically the one change i did for the sample application:

- https://github.com/awesome-inc/FontAwesome.Sharp/compare/net5
