### ISSUE TITLE
Most of Icons does not appear on .Net Core 3.1 Windows Forms App

### ISSUE THREAD

**Issue by Ghassenbbb** [awesome-inc/FontAwesome.Sharp#47]
Hello,
I've installed FontAwesome.Sharp from NuGet Package Manager on a fresh .Net Core 3.1 Windows Forms App Project,
I can create Icon Buttons but only few Icons appear.

**Comment by mkoertgen** [comment]
Hi @Ghassenbbb,

In Designer they don't show up as of now. In runtime they should.

**Comment by Ghassenbbb** [comment]
> Hi @Ghassenbbb,
> 
> In Designer they don't show up as of now. In runtime they should.

I've tested it on Runtime too and still does not appear.

**Comment by mkoertgen** [comment]
Ok, could be related to #46 . Probably the unicodes changed and we have to regenerate the enums.

**Comment by mkoertgen** [comment]
Can you list some icons that definitely don't show up, e.g. FaCogs? That would make it easier to review & check.

**Comment by Ghassenbbb** [comment]
I noticed that most of Icons that works are Brand Icons, and None of User Interface Icons works.
Here is few Icons names that Does not Work : 

- Trailer
- Bacteria
- Bacterium
- BoxTissue
- HandHoldingMedical
- HandSparkles
- HandsWash
- HandshakeAltSlash
- HeadSideCough
- Search
- Heart
- Tasks
- Filter
- Briefcase
- Link
- Cloud
- Flask
- Cut
- Copy
- Paperclip
- ListUl
- ... AND MORE

These ones works fine :

- BattleNet
- Centercode
- Jira
- Whmcs
- Unity
- Uikit
- Uber

**Comment by mkoertgen** [comment]
Ah, ok that makes sense. The brands-section did change over the last few releases. 
However i would not have expected that some basic icons like Copy, PaperClip change their unicode-values in the release-process of fortawesome.

I will regenerate and publish a 5.14.1 today then. Thanks!

**Comment by Ghassenbbb** [comment]
Thanks @mkoertgen 
This is truly above and beyond. Keep it up

**Comment by mkoertgen** [comment]
Hi @Ghassenbbb , i just checked. The unicode-values did not change. Sadly, it seems to be a winforms-issue because WPF works fine.

**Comment by mkoertgen** [comment]
Just sample-checked winforms elements **dropdown**, **menuitem**, ... with Trailer, Bacteria & Bacterium, .... 

Works without problems.

![image](https://user-images.githubusercontent.com/7235760/91046782-51d97c80-e619-11ea-96f0-c3bb6b44fc95.png)

What elements did you notice with problems?

**Comment by Ghassenbbb** [comment]
I have only IconButton and IconPictureBox, I'm having the same issues on both of them.

![wz](https://user-images.githubusercontent.com/68383748/91085986-89165080-e64e-11ea-933d-9dc305b54c1a.png)

**Comment by mkoertgen** [comment]
Thanks for getting back. I will double check IconButton/PictureBox.

**Comment by FoxCouncil** [comment]
The reason the brand icons are working is because the [FallbackFont](https://github.com/awesome-inc/FontAwesome.Sharp/blob/ef71643ca08ce47516404180e1821913bed98fce/FontAwesome.Sharp/WinForms/FormsIconHelper.cs#L19) ends up being the `fa-brands-400.ttf` font.

The [Typeface.TryGetGlyphTypeface(GlyphTypeface)](https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.typeface.trygetglyphtypeface?view=netcore-3.1) method always returns false and the `GlyphTypeface` is always `null` [here](https://github.com/awesome-inc/FontAwesome.Sharp/blob/18cd5ed1a6e566b2ae9688e68e71d43622eb6cf5/FontAwesome.Sharp/WPF/IconHelper.cs#L81). This is the primary reason the font doesn't switch to the correct one and only works with brand `IconChar`'s.

I'm now trying to determine why [Typeface.TryGetGlyphTypeface(GlyphTypeface)](https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.typeface.trygetglyphtypeface?view=netcore-3.1) is not returning the same results as `.NET Framework` vs `.NET Core`

**Comment by mkoertgen** [comment]
@FoxCouncil great work. Thanks man!

**Comment by aeonSolutions** [comment]
just built from source last commit however is still not working .
here's what i got:

![devenv_myCnxcbQKB](https://user-images.githubusercontent.com/7936768/91645547-38d03180-ea46-11ea-8550-2fb2036a90b5.png)

**Comment by FoxCouncil** [comment]
With the latest `git` commit, locally packed up into a nuget, and `.NET 3.1` WinForms. I'll give `.NET 5` a test soon...

Working both in `Design Time` and `Runtime` for me.

`Microsoft Visual Studio Enterprise 2019`
`Version 16.7.2`

![image](https://user-images.githubusercontent.com/6202482/91672784-3b359880-eae5-11ea-9d43-4e451a5285fa.png)
![image](https://user-images.githubusercontent.com/6202482/91672792-4d173b80-eae5-11ea-9d76-c669f8a7d096.png)
![image](https://user-images.githubusercontent.com/6202482/91672800-57d1d080-eae5-11ea-895e-86ba4c2b9403.png)

**Comment by Ghassenbbb** [comment]
@FoxCouncil 
Please when the fix will be available on NuGet.org ?

**Comment by mkoertgen** [comment]
@FoxCouncil @Ghassenbbb If you agree that the last commit is working for you we can push a release in the next hour

**Comment by Ghassenbbb** [comment]
@mkoertgen Excuse me, I don't know how to install the new fix from Github (I tried) , that's why im asking for a NuGet Package Update.

**Comment by mkoertgen** [comment]
Ok, no problem. I will push an update.

**Comment by Ghassenbbb** [comment]
@mkoertgen @FoxCouncil 
Thank you, great work, it works fine now.
