### ISSUE TITLE
Application not runnig on another PC

### ISSUE THREAD

**Issue by josdar** [awesome-inc/FontAwesome.Sharp#50]
Do I need to install a font or something in the other PC if I want to run my application with the executable and not from Visual Studio.

**Comment by mkoertgen** [comment]
Hi @josdar ,

The free fontawesome fonts are embedded as resources into the compiled app so it can run anywhere without any font redistribution.

**Comment by josdar** [comment]
That's what I though, but it only launches if I include the FontAwesome.Sharp.dll in the same folder as the compile app

**Comment by mkoertgen** [comment]
Yes right. The FontAwesome.Sharp.dll contains the fonts and the code. 
Usually you would deploy the complete output directory, i.e. `bin\Debug` or `bin\Release`

**Comment by josdar** [comment]
Oh Ok thanks for the help
