### ISSUE TITLE
Want to Create an Application showing Images

### ISSUE THREAD

**Issue by LukB4ULeap** [awesome-inc/FontAwesome.Sharp#53]
I am trying to Create a WindowsForm Core Application that shows all the Images with Name in the form and keep it as Reference because dropdown calls for a lengthy search.
Can I get some help? 
When you Open my Application you  will have an Alphabet Selector based on this 
I want to show PictureBoxes with the Image(IconChar) and a Label below that has its name use this as a quick reference while using your Framework.

**Comment by mkoertgen** [comment]
Hi @LukB4ULeap ,

thanks for reaching out. Try the autocomplete mode of the standard winforms textbox. You should be able to just add all enumvalues to the source collection, cf.:
- https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.combobox.autocompletemode?view=netcore-3.1
