### ISSUE TITLE
How can I add Icons ?

### ISSUE THREAD

**Issue by LukB4ULeap** [awesome-inc/FontAwesome.Sharp#55]
I created a tool that shows 
![FontAwesomeclientAssistant](https://user-images.githubusercontent.com/15842158/98717673-3c374180-2342-11eb-9828-38d7d9a4c286.gif)

I searched for some Icons related to Database Operations, UI Operations I don't think they exist in the Repository; In case I want to Add Icons of my Own what is the way to do this.

**Comment by mkoertgen** [comment]
Hi @LukB4ULeap , 
Adding icons to the webfont is documented in the main fontawesome project here
- https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md
