### ISSUE TITLE
Help with Input Fonts

### ISSUE THREAD

**Issue by sbridgens** [awesome-inc/FontAwesome.Sharp#58]
I am using this fantastic product you created in a winforms app and have found that whenever an input control is added the control size and font is decreased to what I would assume to be around a font size of 6.

The following entry was added to the app.config however this did not resolve the issue:
 <System.Windows.Forms.ApplicationConfigurationSection>
    <add key="DpiAwareness" value="PerMonitorV2" />
  </System.Windows.Forms.ApplicationConfigurationSection>

In order to demonstrate this issue the following can be done:

1: Create a basic winform app
2: Add the following controlls - Button, Label, Textbox, Richtextbox
3: change the font for each control to: Microsoft Sans Serif, 12pt
4: Add text to each control i used the same value of: "Microsoft Sans Serif, 12pt"
5: Run - everything should appear fine.
6: Install the Fontawesome.sharp nuget package
7: Add an IconButton to the form
8: Run the application and the input controls will shrink in size/font.

Hopefully, this is a merely a setting I missed or need to consider?

**Comment by sbridgens** [comment]
Close, for now, I rolled back the framework; restarted vs 2019 rebuilt and then rolled forward again and for some reason every thing is fine again so I suspect this is related to dpi and toying with the frameworks managed to resolve the issue?

**Comment by mkoertgen** [comment]
Hi Simon, thanks for reaching out. 
From our experience DPI scaling can be complicated with WinForms. In fact, we had some issues reported affecting the overall scaling of a windows forms app, probably related to the point where the fontawesome fonts get loaded into memory.
In the end it seemed to be mostly Heisenbugs, i.e. we never could lay our finger on it.
Let me know if this bugs you again or find out something about this.
