### ISSUE TITLE
FontAwesome.Sharp.Pro support for Win Forms

### ISSUE THREAD

**Issue by diox8tony** [awesome-inc/FontAwesome.Sharp#60]
Add Winforms support in FontAwesome.Sharp.Pro

ps: I'm sorry if this already exists and I couldn't find it, or how to make it work. After seeing the source code for FontAwesome.Sharp have folders for both WinForms and WPF, but the Pro source only has Winforms I assumed that was the end of my road. If I am wrong, Does anyone have documentation to get Pro Icons in Winforms (IconButton class used)

**Comment by mkoertgen** [comment]
Hi @diox8tony ,

Did you have a look at the FAQ? There is a small section on how to get pro-font up & running:
-  https://github.com/awesome-inc/FontAwesome.Sharp#using-fontawesome-pro
