### ISSUE TITLE
WPF: New property IconFont in IconImage

### ISSUE THREAD

**Issue by mschulze46** [awesome-inc/FontAwesome.Sharp#61]
At first many thanks for your efforts!

For a WPF project I really would like to use the latest version but I cannot find the new property IconFont in IconImage objects.
Looking at the sources I only see the IconFont property in the WinForms section. Is it not available for WPF?

How to switch easily between the icon styles in WPF?

![2021-01-13 14_07_24-GitHub - awesome-inc_FontAwesome Sharp_ A library for using Font Awesome in WPF ](https://user-images.githubusercontent.com/30439703/104456772-7377d800-55a9-11eb-96a5-6cb5ca47d949.png)

Many thanks in advance!
Michael

**Comment by mkoertgen** [comment]
Hi @mschulze46 , 

Yes exactly. The initial implementation was only carried out for WinForms as there has been the most traction lately.

It should be straight forward to add this for WPF as well. Should we? Would you also be willing to contribute in this regard?

**Comment by mschulze46** [comment]
> 
> 
> Hi @mschulze46 ,
> 
> Yes exactly. The initial implementation was only carried out for WinForms as there has been the most traction lately.
> 
> It should be straight forward to add this for WPF as well. Should we? Would you also be willing to contribute in this regard?

I really would love to do so but on the one hand I have a ton of work right now and on the other hand I'm in WPF for just a few months now. I don't know if this would work out... ;)
