### ISSUE TITLE
Only IconButton and IconPictureBox controls, no IconDropDownButton

### ISSUE THREAD

**Issue by DannyDannyDan** [awesome-inc/FontAwesome.Sharp#62]
Hi, I've downloaded the latest code and am having some issues with the TestForms project.  If I start debugging the project, the IconDropDownButton appears, however, I can't see the IconDropDown or a few other controls in the designer.

Also, if I install the FontAwesome.Sharp nuget package into other projects, I only get IconButton and IconPictureBox controls in the toolbox.  Am I suppose to hand edit the designer file to use the other controls, or am I suppose to make my own user controls, or is this a bug?

![Clipboard01](https://user-images.githubusercontent.com/30601028/105941264-a8ad0d00-6022-11eb-89bc-a451e7b84141.png)

**Comment by mkoertgen** [comment]
Hi @DannyDannyDan ,

Designer support should usually be available, however we never spent much effort on supporting a full-fledged designer experience.

So you may run into issues when the Designer tries to create the controls. It needs a parameterless ctor and loading the fonts into memory on the static constructors can cause trouble, especially when the hosting process is some more recent version of VisualStudio.

We started with WPF and added WinForms along the way to support some legacy applications. 
We notice that recently the project gains much more interest in the WinForms community so we are aware that we lack a bit of support on this.

**Comment by mkoertgen** [comment]
@DannyDannyDan i just checked the project myself and it looks the same for me, so let's declare it a bug.

![image](https://user-images.githubusercontent.com/7235760/105992488-7bee0980-60a5-11eb-8c95-65c14c681acb.png)

**Comment by mkoertgen** [comment]
@DannyDannyDan I labeled it also as **up-for-grabs**, so if you are inclined to contributing back and have interest and some time to spare we would love to accept some diagnostics insight, maybe even a pull request fixing the issue.

**Comment by mkoertgen** [comment]
Some information to get us going:
- open issue on how to detect designmode: https://github.com/dotnet/winforms/issues/3300
   - mentioned on SO here: https://stackoverflow.com/a/65849349/2592915
- using designer attributes in this repo: https://github.com/awesome-inc/FontAwesome.Sharp/search?q=designer
- [ ] check winforms designer on/off: https://devblogs.microsoft.com/dotnet/windows-forms-designer-for-net-core-released/

![image](https://user-images.githubusercontent.com/7235760/105993443-b73d0800-60a6-11eb-8382-0ec5573b6051.png)

- https://docs.microsoft.com/en-us/dotnet/desktop/winforms/controls/walkthrough-debugging-custom-windows-forms-controls-at-design-time?view=netframeworkdesktop-4.8

**Comment by DannyDannyDan** [comment]
I'd like to help but it will be quite some time before I have spare time.

**Comment by ClubberLangG** [comment]
Hi,

Still no news about this issue ? 

I've just downloaded the last nuget and there is no IconToolStripButton in the designer :-(

Thx

**Comment by mkoertgen** [comment]
Tried reproducing it. Manually adding the package-dll to the toolbox results in

![image](https://user-images.githubusercontent.com/7235760/184112623-b4a6c426-da89-4ed6-b6e9-b07fd1ce5ac5.png)

**Comment by mkoertgen** [comment]
Researching this issue I found which describes the change behavior with net-core

- https://stackoverflow.com/a/71523391/2592915
- https://developercommunity.visualstudio.com/t/toolboxs-choose-items-still-cannot-browse-a-winfor/1141745
- https://github.com/microsoft/xaml-designer-extensibility/blob/main/documents/toolbox-population.md

Let's try adding a toolbox manifest as outline here

- https://github.com/microsoft/xaml-designer-extensibility/blob/main/documents/toolbox-population.md#how-to-build-our-wpf-net-core-sample-package
- https://docs.microsoft.com/en-us/nuget/guides/create-ui-controls
