### ISSUE TITLE
Using this library on C++ winforms

### ISSUE THREAD

**Issue by guzzyEZ** [awesome-inc/FontAwesome.Sharp#63]
Hello, I am kinda new to programming, so forgive me if I'm asking a dumb question, but I was wondering if it was possible to use this in a C++/winforms project. Thanks :)

**Comment by mkoertgen** [comment]
Hy @guzzyEZ ,
It probably might, ;-). You talk about a mixed-mode assymble using WinForms?

- https://docs.microsoft.com/en-us/cpp/dotnet/mixed-native-and-managed-assemblies?view=msvc-160

**Comment by mkoertgen** [comment]
Closed due to inactivity.
