### ISSUE TITLE
Doesn't work with .NET Core WinForms C# on VS 2019 Community Edition

### ISSUE THREAD

**Issue by MithunChopda** [awesome-inc/FontAwesome.Sharp#64]
I installed the FontAwesome.Sharp nuget package into a .NET Core C# Win Forms application in VS 2019. The package get added but the controls do not reflect on Toolbox. Nor is it available to be added in Toolbox >> Right Click >> Choose Items... section. I see only the IconButton listed under Universal Windows Components Tab on Choose Items.. dialog. Including the IconButton that appears under Universal Windows Components doesn't reflect any change.

**Comment by mkoertgen** [comment]
Hi @MithunChopda ,

There is an entry in the FAQ related to this.
Did you check it?

**Comment by mkoertgen** [comment]
Closed due to inactivity.
