### ISSUE TITLE
Sometimes, Icons in IconButton dont show up

### ISSUE THREAD

**Issue by bsanie** [awesome-inc/FontAwesome.Sharp#71]
for some reason, when running the application. Icons dont appear! Below two screenshots show when icons are shown and they are not.

![image](https://user-images.githubusercontent.com/87239057/126245958-4f7602c7-b527-4e03-98fa-d74d3ee2fedd.png)

![image](https://user-images.githubusercontent.com/87239057/126246048-29b82dc0-0d35-4404-a92f-78f32bb004fc.png)

**Comment by mkoertgen** [comment]
Hi @bsanie ,

Thanks for reaching out. Let's triangulate the problem:

- Are you observing this using WinForms or WPF?
- Which .NET-Version / OS-Version did you observe this on?
- Which version of the library do you use?
- Any AntiVirus-scanners probably interfering with the fonts loaded into memory?
- Have you scanned other (probably closed) issues for similar problems? 
- How about log messages? The library should trace some warnings in case it can't find icons or load fonts.

I remember a similar issue that was to do with using another complementary font-glyph-library for MaterialDesign.

**Comment by bsanie** [comment]
> Hi @bsanie ,
> 
> Thanks for reaching out. Let's triangulate the problem:
> 
> * Are you observing this using WinForms or WPF?
> * Which .NET-Version / OS-Version did you observe this on?
> * Which version of the library do you use?
> * Any AntiVirus-scanners probably interfering with the fonts loaded into memory?
> * Have you scanned other (probably closed) issues for similar problems?
> * How about log messages? The library should trace some warnings in case it can't find icons or load fonts.
> 
> I remember a similar issue that was to do with using another complementary font-glyph-library for MaterialDesign.

**Comment by bsanie** [comment]
Hello @mkoertgen 
Thanks for your comment. 
My bad, I didnt scan closed issues for the same issue i had.  I found the solution in this thread https://github.com/awesome-inc/FontAwesome.Sharp/issues/65 

all i did is solve this issue is to set IconFont explicitly.

**Comment by bsanie** [comment]
Hi @mkoertgen 
Looks like my problems are execatly like the guy in this thread https://github.com/awesome-inc/FontAwesome.Sharp/issues/65

After setting IconFont to Solid, i started (Sometimes, not always,) getting an exception that says "Value cannot be null.\r\nParameter name: family" 

is there a solution or workaround for this?

**Comment by mkoertgen** [comment]
Hi @bsanie ,

Font awesome is a bit peculiar about icon-sets are mapped to separate font styles / family. 

If you show icons in a static manner, be sure to check the icon sheet
- https://fontawesome.com/v5.15/icons?d=gallery&p=2&m=free

For dynamic scenarios the `auto`-style will try to find (and cache) your icon in the respective fonts / styles.

**Comment by bsanie** [comment]
Thanks @mkoertgen,
All my issues with FrontAwesome.Sharp are resolved.
