### ISSUE TITLE
Can not compile the project

### ISSUE THREAD

**Issue by mohelsheikh** [awesome-inc/FontAwesome.Sharp#72]
Thank you so much for your post, i really wish to use it
i have a lot of issues to compile the project. i used VS 2017 & 2019 and no luck to successfully build the project

do you have any instructions or perroquets to build the project

thanks

**Comment by mohelsheikh** [comment]
Please find attached the log file and a screenshot of the error
[Log.txt](https://github.com/awesome-inc/FontAwesome.Sharp/files/6858487/Log.txt)

![image](https://user-images.githubusercontent.com/3342362/126551895-1e7147b3-532a-4baa-8f95-a41361d7f99c.png)

**Comment by mkoertgen** [comment]
The highlighted compile error refers to the new target-typed new-expression introduced in C# 9.0 (still beta), cf.:
- https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/target-typed-new

Updating your VS and dotnet-sdk (>= 5) to the newest version should suffice to build the project, cf.:
- [./global.json](https://github.com/awesome-inc/FontAwesome.Sharp/blob/master/global.json)

**Comment by mkoertgen** [comment]
Closed due to inactivity.
