### ISSUE TITLE
I can't see elements in toolbox

### ISSUE THREAD

**Issue by juanm4** [awesome-inc/FontAwesome.Sharp#8]
Hi, It's probably that I don't know how do it...but, how Can I show the objects (for example "IconButton") in the toolbox of visual studio?

I have realized that I can put an IconButton making a copy-paste from the project sample, but I don't see IconButton in toolbox. 

Thanks in advance!

**Comment by mkoertgen** [comment]
Ah, common problem with WinForms.
Check out the FAQ section in the README 

- https://github.com/awesome-inc/FontAwesome.Sharp/blob/develop/README.md#windows-forms-designer-i-cannot-find-any-controls-in-the-toolbox

You would have to scroll waaay down, 😉

Let me know if that helped

**Comment by juanm4** [comment]
First of all, thanks for your response, but I haven't found the controls in toolbox. I have tried to find and add the controls (Toolbox -> right click -> Choose Items -> Browse) but I can't find the controls in any of four tab appeared.

Some tips?

Thanks!

**Comment by mkoertgen** [comment]
Not really any more tips than disccussed in the referenced links, i.e.

1. Create a new Windows Forms App
2. Add FontAwesome.Sharp as a Nuget dependency: `Install-Package FontAwesome.Sharp` (as of now should be `4.7.1`)
3. In the Toolbox:
    - Add a tab *FontAwesome* (optional) or select a tab where you want the items to appear
    - Next, add items to the tab, i.e. *Choose Items* -> *Browse*, then select `$(SolutionDir)./packages\FontAwesome.Sharp.4.7.1\lib\net40\FontAwesome.Sharp.dll`
    - You should then see at least 2 new items selected
![image](https://user-images.githubusercontent.com/7235760/35670173-02f3e230-0738-11e8-8330-a29f5ffcebcd.png)
    - Click Ok. 

You should now see controls in the selected toolbox tab, like

![image](https://user-images.githubusercontent.com/7235760/35670387-bd402234-0738-11e8-9b46-3add8557a581.png)

Let me know, if that helps.

**Comment by juanm4** [comment]
Perfect! It work like a charm. I don't know why, but before I tried it in the same way and visual studio show an error when I tried to add the .dll.

After restart so and reopen visual studio I followed your steps carefully and it worked!!!

Thanks for all!
