### ISSUE TITLE
Cannot add reference to FontAwesome.Sharp at run time of excel-VSTO add-in

### ISSUE THREAD

**Issue by VanBuren77** [awesome-inc/FontAwesome.Sharp#89]
**Describe the bug**
Cannot add reference to FontAwesome.Sharp at run time of excel-VSTO add-in

**To Reproduce**
1. Download Microsoft Office SDK toolkit
2. Create a new Excel VSTO Add-in project inside of Visual Studio
3. Install FontAwesome.Sharp via NuGet
4. Add a ribbon designer object to project
5. Add a user form designer object to project
6. Put a button on ribbon designer 
7. Add FontAwesome.Sharp icon button to user form designer
8. On click event of the button, instantiate a new form1 class
9. Show the form

**Expected behavior**
Popping up the userform that depends on FontAwesome.Sharp should work, and it should find the reference

**Screenshots**
![image](https://user-images.githubusercontent.com/20358136/162513887-b9d9abb2-53a4-4bfb-8b6b-6a08fde79561.png)

**Desktop (please complete the following information):**
 - Windows 10

**Additional context**
Trying to make excel-VSTO add in that can spawn generic windows forms that use FontAwesome.Sharp

**Comment by mkoertgen** [comment]
Hi @VanBuren77,

Have a look at https://github.com/awesome-inc/FontAwesome.Sharp#strong-name-signing-eg-for-clickonce-publishing

**Comment by VanBuren77** [comment]
Thanks, I'll take a look. Need to understand implications too. I am using this for ClickOnce publishing. It looks like the StrongNameSigner from Brutaldev is pretty old but might be a fix.

If StrongNameSigner doesn't work or alternatives, then unfortunately, I can't use FontAwesome.Sharp and I'll do things manually.

**Comment by mkoertgen** [comment]
Version 3.0.1 of [StrongNameSigner](https://github.com/brutaldev/StrongNameSigner) is pretty recent and should do the trick. 

As far as I know, publishing an Office-AddIn requires all assemblies to be strong-named. 
So once you add any other non-signed library you will probably want to include signing as an after-build step anyway.

Office-AddIns were tough back in 2015. I don't know whether this has become any better. Stay strong!

**Comment by mkoertgen** [comment]
We will add strong name signing in v6+
