### ISSUE TITLE
Facing a problem from Long Time

### ISSUE THREAD

**Issue by Magnifo** [awesome-inc/FontAwesome.Sharp#90]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Hello Sir,
I have an issue when I add IconButton form fontAwesomesharp to my form and run it, the form scaling is changed and it appears much smaller than its original size, could you help me with this problem?

**Comment by mkoertgen** [comment]
Hi @Magnifo ,
I think this is not unknown behavior. Maybe you can try configuring DPI Awareness as described in the FAQ, cf.

- https://github.com/awesome-inc/FontAwesome.Sharp#my-windows-forms-application-gets-rescaled-once-a-fontawesome-item-is-created

**Comment by mkoertgen** [comment]
Closed as stale
