### ISSUE TITLE
FontAwesome Tab doesn't appear on Toolbox (Winform App .NET Framework 4.8) 

### ISSUE THREAD

**Issue by minhman2501** [awesome-inc/FontAwesome.Sharp#91]
After installing the FontAwesome.Sharp in my winform .NET project, the FontAwesome tab still doesn't appear on the Toolbox

I have installed it
![image](https://user-images.githubusercontent.com/90081072/168412790-807bc224-e382-4bdc-886c-c4f7c8f21464.png)

nothing changed in the toolbox
![image](https://user-images.githubusercontent.com/90081072/168412807-050933e3-ad88-4af2-8033-3c0fa5b36f19.png)

**Comment by mkoertgen** [comment]
Hi @minhman2501 ,

This is a known issue. Have a look at https://github.com/awesome-inc/FontAwesome.Sharp#windows-forms-designer-i-cannot-find-any-controls-in-the-toolbox

**Comment by mkoertgen** [comment]
Will need to add a vstoolbox-manifest: https://docs.microsoft.com/en-us/nuget/guides/create-ui-controls

**Comment by mkoertgen** [comment]
What worked was adding a ToolboxItemAttribute
