### ISSUE TITLE
Missing/Error Fonts

### ISSUE THREAD

**Issue by Sensei6x9** [awesome-inc/FontAwesome.Sharp#93]
**Describe the bug**
Using VB WinForms, I updated to v6.1.1, and most of the icons I used is being displayed as box with an 'X' inside.

**Screenshots**
![image](https://user-images.githubusercontent.com/96456175/179130417-1e8b68b3-0d06-4d14-ab15-bbfc307bc1cb.png)

**Desktop (please complete the following information):**
 - OS: Win11
 - Browser: Chrome
 - Version: 6.1.1

**Comment by mkoertgen** [comment]
Hi @Sensei6x9 ,

Could you provide some more details? Are you using the [IconButton](https://github.com/awesome-inc/FontAwesome.Sharp/blob/main/FontAwesome.Sharp/WinForms/IconButton.cs)-control?

Which icons exactly are you using for "View", "Publish" and "Batch Publish", cf.:
- https://github.com/awesome-inc/FontAwesome.Sharp/blob/main/FontAwesome.Sharp/IconChar.cs

**Comment by mkoertgen** [comment]
Closed due to missing responses.
