### ISSUE TITLE
Duplicate IconChar entries in property window.

### ISSUE THREAD

**Issue by Sensei6x9** [awesome-inc/FontAwesome.Sharp#97]
**Describe the bug**
There are some duplication of IconChars in the property window.

**To Reproduce**
1. Create VB.Net (BASIC) Project
2. Install FA.Sharp v6.1.1
3. Add IconButton
4. Navigate to IconChar in property window.
5. See Error (duplicate IconChars i.e. DollarSign, FloppyDisk, etc.)

**Expected behavior**
Information on why there are duplicates and maybe deletion of the said duplicates.

**Screenshots**
![image](https://user-images.githubusercontent.com/96456175/183252383-f1f81dfe-75ce-46c9-8cb3-fa2cb03ac51a.png)
![image](https://user-images.githubusercontent.com/96456175/183252392-904eae23-63c4-4fea-b4d3-02f28ed96405.png)

**Comment by mkoertgen** [comment]
Hi @Sensei6x9 ,

I can see duplicate enum values for DollarSign in `IconChar.cs` as well as in the Professional-icons (DuoTone, ProIcons), cf.:
- https://github.com/awesome-inc/FontAwesome.Sharp/search?q=DollarSign

`FloppyDisk` only found once in code.

Will check on reproducing the bug.

**Comment by Sensei6x9** [comment]
Thanks @mkoertgen . I'm using only the free one, I guess that why I can only use one of those duplicates.

**Comment by mkoertgen** [comment]
I can confirm this reproducing it using VS2022 / WinForms net6-windows and the latest NuGet package

Lots of duplicate all through the collection
![image](https://user-images.githubusercontent.com/7235760/184105434-73f895fa-0cb9-4c75-84d3-ae098c54b8de.png)

**Comment by mkoertgen** [comment]
Added a unit test reproducing the error. In fact `Enum.GetValues(...). -> ToString()` may produce lots of duplicates.

**Comment by Sensei6x9** [comment]
I don't know what to do from here on out.... still new to github and I'm only here because of your awesome icons (thanks btw)

**Comment by mkoertgen** [comment]
Hi @Sensei6x9 ,

No problem, thanks for bringing this to my attention. The bug is fixed, yet for the next release I wanted to compile some other fixes as well. 

See [milestone 6.1.2](https://github.com/awesome-inc/FontAwesome.Sharp/milestone/5) which should be released by this week. 

Ok for you?

**Comment by Sensei6x9** [comment]
I see, yeah that's great. Thank you so much.

**Comment by duckdoom5** [comment]
The issue is still apparent in a different form. Not sure if you fixed it elsewhere, but the main branch still has duplicate entries.
![image](https://github.com/awesome-inc/FontAwesome.Sharp/assets/1145038/6206798b-5de8-4e4d-9a2d-5872998bdd58)
![image](https://github.com/awesome-inc/FontAwesome.Sharp/assets/1145038/f13a7845-f429-477a-bb35-bcb8f7c77130)

(Note that this is only an intellisense error and compiles just fine)
